<?php
/**
 * Created by PhpStorm.
 * User: xkq72
 * Date: 2019/5/14
 * Time: 16:41
 */

namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
   protected function initialize()
   {
       parent::initialize(); // TODO: Change the autogenerated stub
       define('IS_POST',$this->request->isPost());
   }
}